### ISSUE TITLE
Plotter holding for sync

### ISSUE THREAD

**Issue by Choikyungho9** [shubhamchaudharybrg/Vision#1]
Hello.

I am experimenting with your project.

However, there is one problem.

When I run Lidar_view.py it says'Plotter holding for sync....' and nothing happens.

The terminal command is python3 Lidar_view.py.

What the hell am I doing wrong? Should I create an EOS.txt file? I'm not sure how. I need help.

**Comment by shubhamchdhary** [comment]
Hello!
This is because both the Lidar_view.py and the mainFile.py need to be run simultaneously so that mainFile generate data.csv with  point cloud data which is then used by Lidar_view.py to generate plot.

So, run both programs in separate terminals simultaneously.

**Comment by shubhamchdhary** [comment]
> Hello.
> 
> I am experimenting with your project.
> 
> However, there is one problem.
> 
> When I run Lidar_view.py it says'Plotter holding for sync....' and nothing happens.
> 
> The terminal command is python3 Lidar_view.py.
> 
> What the hell am I doing wrong? Should I create an EOS.txt file? I'm not sure how. I need help.
You need not create any file (like EOS.txt, dat.csv, etc). All are generated by the program automatically.
